DROP TABLE IF EXISTS CATEGORIES;
DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS APPLICATIONS;
DROP TABLE IF EXISTS APPLICATIONS_CATEGORIES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS USERS_APPLICATIONS;

CREATE TABLE "ROLES"
(
  "ID" INT NOT NULL,
  "NAME" VARCHAR(255) NOT NULL,
  CONSTRAINT "ROLES_PKEY" PRIMARY KEY ("ID")
);

CREATE TABLE "CATEGORIES"
(
  "ID" INT NOT NULL,
  "NAME" VARCHAR(255) NOT NULL,
  CONSTRAINT "CATEGORIES_PKEY" PRIMARY KEY ("ID")
);

CREATE TABLE "APPLICATIONS"
(
  "ID" BIGINT AUTO_INCREMENT NOT NULL,
  "NAME" VARCHAR(255) NOT NULL,
  "DOWNLOADED_TIMES" INT NOT NULL DEFAULT '0',
  CONSTRAINT "APPLICATIONS_PKEY" PRIMARY KEY ("ID")
);

CREATE TABLE "APPLICATIONS_CATEGORIES"
(
  "APPLICATION_ID" INT NOT NULL,
  "CATEGORY_ID" INT NOT NULL,
  CONSTRAINT "APPLICATIONS_APPLICATION_ID_fkey" FOREIGN KEY ("APPLICATION_ID") REFERENCES APPLICATIONS ("ID"),
  CONSTRAINT "CATEGORIES_CATEGORY_ID_fkey" FOREIGN KEY ("CATEGORY_ID") REFERENCES CATEGORIES ("ID")
);

CREATE TABLE "USERS"
(
  "ID" INT AUTO_INCREMENT NOT NULL,
  "NAME" VARCHAR(255) NOT NULL,
  "ROLE_ID" INT NOT NULL,
  CONSTRAINT "USERS_PKEY" PRIMARY KEY ("ID"),
  CONSTRAINT "USERS_FKEY" FOREIGN KEY ("ROLE_ID") REFERENCES "ROLES" ("ID")
);

CREATE TABLE "USERS_APPLICATIONS"
(
  "USER_ID" INT NOT NULL,
  "APPLICATION_ID" INT NOT NULL,
  CONSTRAINT "USERS_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES USERS ("ID"),
  CONSTRAINT "APPLICATIONS_APPLICATION_ID2_fkey" FOREIGN KEY ("APPLICATION_ID") REFERENCES APPLICATIONS ("ID")
);
