INSERT INTO ROLES (ID, NAME) VALUES (1, 'USER');
INSERT INTO ROLES (ID, NAME) VALUES (2, 'DEVELOPER');

INSERT INTO CATEGORIES (ID, NAME) VALUES (1, 'Games');
INSERT INTO CATEGORIES (ID, NAME) VALUES (2, 'Education');

INSERT INTO USERS (NAME, PASS, ROLE_ID) VALUES ('Olga', '123', 1);
INSERT INTO USERS (NAME, PASS, ROLE_ID) VALUES ('Ivan', '1234', 2);
--
-- INSERT INTO APPLICATIONS (NAME, FIlES_PATH) VALUES ('Game of Thrones', 'TEST_PATH');
-- INSERT INTO APPLICATIONS_CATEGORIES (APPLICATION_ID, CATEGORY_ID) VALUES (1, 1);
-- INSERT INTO APPLICATIONS_CATEGORIES (APPLICATION_ID, CATEGORY_ID) VALUES (1, 2);