INSERT INTO ROLES (ID, NAME) VALUES (1, 'user');
INSERT INTO ROLES (ID, NAME) VALUES (2, 'developer');

INSERT INTO CATEGORIES (ID, NAME) VALUES (1, 'games');
INSERT INTO CATEGORIES (ID, NAME) VALUES (2, 'education');

INSERT INTO USERS (NAME, ROLE_ID) VALUES ('Olga', 1);
INSERT INTO USERS (NAME, ROLE_ID) VALUES ('Ivan', 2);

INSERT INTO APPLICATIONS (NAME) VALUES ('Game of Thrones')